export const SF_SUPPORTED_FIELDS = [
  'person_type',
  'first_name',
  'last_name',
  'email',
  'email_confirm',
  'job_title',
  'company_name',
  'company_number',
  'vat_number',
  'fiscal_code',
  'phone',
  'address1',
  'address2',
  'town',
  'zip',
  'different_shipping',
  'shipping_address2',
  'shipping_town',
  'shipping_country',
  'shipping_zip',
  'payment_method',
  'agreements1',
  'agreements2',
  'agreements3',
  'payment_options — used for GMO CVS payments',
  'sdi_code',
  'address_pec',
];

export const SF_SUPPORTED_FIELDS_ITEMS = SF_SUPPORTED_FIELDS.map((field) => ({
  value: field,
  label: field,
}));
