// for demo

export const initialFields = [
  {
    id: 'first_name',
    name: 'first_name',
    type: 'text',
    default_value: '',
    default_hidden: false,
    default_readonly: false,
    label: 'First Name',
    tech_show_validation: true,
    tech_use_custom_name: false,
    tech_custom_name: '',
    tech_section: 'contact_info',
    required: true,
    min_length: 4,
    max_length: 10,
    pattern: '',
    validators: [],
  },
  {
    id: 'last_name',
    name: 'last_name',
    type: 'text',
    default_value: '',
    default_hidden: false,
    default_readonly: false,
    label: 'First Name',
    tech_show_validation: true,
    tech_use_custom_name: false,
    tech_custom_name: '',
    tech_section: 'contact_info',
    required: true,
    min_length: 4,
    max_length: 10,
    pattern: '',
    validators: [],
  },
  {
    id: 'email',
    name: 'email',
    type: 'textWithAlert',
    default_value: '',
    default_hidden: false,
    default_readonly: false,
    label: 'Email',
    tech_show_validation: true,
    tech_use_custom_name: false,
    tech_custom_name: '',
    tech_section: 'contact_info',
    required: true,
    min_length: 4,
    max_length: 10,
    pattern: '',
    validators: [],
  },
  {
    id: 'address1',
    name: 'address1',
    type: 'text',
    default_value: '',
    default_hidden: false,
    default_readonly: false,
    label: 'Address Line 1',
    tech_show_validation: true,
    tech_use_custom_name: false,
    tech_custom_name: '',
    tech_section: 'address_info',
    required: true,
    min_length: 4,
    max_length: 10,
    pattern: '',
    validators: [],
  },
  {
    id: 'address2',
    name: 'address2',
    type: 'text',
    default_value: '',
    default_hidden: false,
    default_readonly: false,
    label: 'Address Line 2',
    tech_show_validation: true,
    tech_use_custom_name: false,
    tech_custom_name: '',
    tech_section: 'address_info',
    required: true,
    min_length: 4,
    max_length: 10,
    pattern: '',
    validators: [],
  },
  {
    id: 'town',
    name: 'town',
    type: 'text',
    default_value: '',
    default_hidden: false,
    default_readonly: false,
    label: 'City',
    tech_show_validation: true,
    tech_use_custom_name: false,
    tech_custom_name: '',
    tech_section: 'address_info',
    required: true,
    min_length: 4,
    max_length: 10,
    pattern: '',
    validators: [],
  },
];

export const initialSections = [
  { id: 'contact_info', name: 'Contact Info', fields: ['first_name', 'last_name', 'email'] },
  { id: 'address_info', name: 'Address', fields: ['address1', 'address2', 'town'] },
];
